flask:
  SECRET_KEY: 'XCKypP-OJ#Pv_`~^ Uag2whI+sw.:"__&AH5_+YP'
flask-security:
  SECURITY_PASSWORD_SALT: '&%V6-9hqdKKNM|AL|4l&-%Z?sp_|OvZ"K-nmfSp!'
spotify:
  CLIENT_ID: 'ID_HERE'
  CLIENT_SECRET: 'SECRET'
  REDIRECT_URI: 'http://localhost/spotify_callback'
